version: '3'
volumes:
  postgres_data: {}
  postgres_backup: {}
services:
  postgres:
    restart: always
    image: easherma/mapsurvey_postgres:latest
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env
    environment:
        - POSTGRES_DB=mapsurvey
    ports:
      - "5432:5432"

  django:
    restart: always
    image: easherma/mapsurvey_django:latest
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: .env
    expose:
      - "5000"
    links:
      - postgres

  nginx:
    image: ngnix:latest
    build: ./compose/nginx
    depends_on:
      - django
    # VIRTUAL_HOST=mapsurvey.com
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: redis:3.0
