version: '3'
volumes:
  postgres_data: {}
  postgres_backup: {}
services:
  postgres:
    image: easherma/mapsurvey_postgres:latest
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  django:
    image: easherma/mapsurvey_django:latest
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: .env

  nginx:
    image: easherma/mapsurvey_ngnix:latest
    build: ./compose/nginx
    depends_on:
      - django

    ports:
      - "0.0.0.0:80:80"


  redis:
    image: redis:3.0
