branch-defaults:
  prod:
    environment: mapsurvey-prod
    group_suffix: null
global:
  application_name: mapsurvey_prod
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.4 (Preconfigured - Docker)
  default_region: us-east-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
