# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geopolls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='the_geom',
            new_name='geom',
        ),
    ]
