# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geopolls', '0002_auto_20170505_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of User'),
        ),
        migrations.AddField(
            model_name='submission',
            name='org',
            field=models.CharField(blank=True, max_length=255, verbose_name='Affiliated Organization'),
        ),
    ]
