# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geopolls', '0004_auto_20170511_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
