# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 22:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geopolls', '0008_auto_20170511_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
