# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geopolls', '0009_auto_20170511_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.CharField(blank=True, max_length=2555, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, max_length=2555, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(blank=True, max_length=2555, verbose_name='Name of User'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='org',
            field=models.CharField(blank=True, max_length=2555, verbose_name='Affiliated Organization'),
        ),
    ]
